create sequence package_handler_seq as integer start with 1 increment by 1;
create sequence tracking_history_seq as integer start with 1 increment by 1;

create table package_handler (
    id integer generated by default as sequence package_handler_seq primary key,
    name varchar(50),
    lastname varchar(50),
    phonenumber varchar(50)
);
create index package_handler_fullname_idx on package_handler (name asc, lastname asc);
create index package_handler_phonenumber_idx on package_handler (phonenumber asc);

create table tracking_history (
    id integer generated by default as sequence tracking_history_seq,
    log_date timestamp not null,
    package_handler_id integer not null,
    latitude double,
    longitude double
);
alter table tracking_history add constraint tracking_history_pk primary key (id);
alter table tracking_history add foreign key (package_handler_id) references package_handler (id);
create index tracking_history_log_date_idx on tracking_history (log_date asc);
