package o.oo.service;

import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class NameRandomizerService implements RandomizerService {

    private static Random rand = new Random();
    /* source: https://wiki.ubuntu.com/DevelopmentCodeNames#List_of_Adjectives_and_Animals */
    private static List<String> adjectives = new ArrayList<String>(Arrays.asList("Able", "Acute", "Adventurous", "Agile",
            "Aggravated", "Alcoholic", "Alliterating", "Amok", "Angelic", "Antsy", "Amazing", "Ambling", "Amenable",
            "Amicable", "Anarchic", "Annoying", "Antidisestablishmentarian", "Androgynous", "Archaic", "Arty", "Atomic",
            "Atrophying", "Awesome", "Aware", "Aztec", "Antlered", "Ballsy", "Batty", "Barking", "Belching",
            "Bellicose", "Bewildered", "Blustering", "Boggling", "Boisterous", "Bonkers", "Bounding", "Brainy", "Brave",
            "Brazen", "Breezy", "Brilliant", "Bright", "Bumpy", "Busy ", "Calculating", "Callous", "Campy", "Canny",
            "Canonical", "Careful", "Cavalier", "Celebrating", "Charming", "Cheeky", "Cheerful", "Cheesy", "Chirping",
            "Chocolate", "Chronic", "Chummy", "Clever", "Clumsy", "Colonel", "Constipated", "Cool", "Courageous",
            "Crabby", "Crafty", "Cranky", "Crazy", "Crooked", "Cruising", "Cuddly", "Culpable", "Cunning", "Cute",
            "Curt", "Dapper", "Dangerous", "Daring", "Dastardly", "Daunting", "Dazzling", "Defiant", "Diligent",
            "Disaffected", "Disorderly", "Dogmatic", "Dreamy", "Drowsy", "Durable", "Dutiful", "Eager", "Early",
            "Earnest", "Easy", "Eccentric", "Eclectic", "Edgy", "Eel", "Eerie", "Effervescent", "Electric", "Eminent",
            "Elegant", "Elite", "Eloquent", "Embraceable", "Enlightened", "Enoumous", "Ergonomic", "Erratic",
            "Euphoric", "Evangelizing", "Exquisite", "Extrovert", "Eked", "Fair", "Fairies", "Fanatical", "Fantastic",
            "Farsighted", "Fast", "Fatuous", "Fecund", "Feisty", "Festive", "Ferocious", "Fierce", "Fiery", "Fishy",
            "Fitchew", "Flamboyant", "Flakey", "Flashy", "Flippant", "Flirty", "Fluent", "Flying", "Foxy", "Freaky",
            "Friendly", "Frisky", "Froody", "Fruity", "Functional", "Funky", "Furious", "Furry", "Fuzzy", "Gaia",
            "Gallant", "Galloping", "Gallus", "Gargantuan", "Gelatinous", "Giddy", "Genderqueer", "Giggling", "Glad",
            "Gleaming", "Gnathonic", "Gnathal", "Gnomic", "Gnostic", "Gooey", "Glorious", "Goofy", "Gol", "Gorgeous",
            "Graceful", "Gracious", "Great", "Greedy", "Gregarious", "Grinning", "Gritty", "Grizzly", "Groovy",
            "Grumpy", "Gutsy", "Happy", "Hairy", "Hardy", "Haughty", "Hazardous", "Helpful", "Helpless", "Hilarious",
            "Hippy", "Hoary", "Holy", "Hoopy", "Hopping", "Horned", "Horny", "Horrible", "Hot", "Huge", "Humble",
            "Humpin", "Howling", "Humourous", "Hungry", "Hyperactive", "Interstellar", "Icky", "Icy", "Idyllic", "Iffy",
            "Ignited", "Igneous", "Illuminating", "Illustrious", "Immodest", "Immortal", "Impressive", "In one's way",
            "In the way", "Incendiary", "Incomparable", "Inconceivable!", "Incontinent", "Incredible", "Incriminatory",
            "Indefatigable", "Industrious", "Indelible", "Inebriated", "Ineffable", "Inescapable", "Inestimable",
            "Inevitable", "Inexorable", "Infallible", "Inflammatory", "Inflationary", "Ingenious", "Ingratiating",
            "Initiatory", "Inky", "Impish", "Inner-city", "Innocent", "Innovatory", "Inquisitive", "Insanitary",
            "Insatiable", "Inscrutable", "Insightful", "Insolent", "Insouciant", "Inspired", "Inspirational",
            "Insurgent", "Intelligent", "Interagency", "Intercalary", "Intercessory", "Intercity", "Intermediary",
            "Intervarsity", "Intimate", "Intimidated", "Intrepid", "Inverted-snobbery", "Irate", "Iridescent", "Irie",
            "Irksome", "Irrefutable", "Itchy Wink", "Itsy", "Investigatory", "Ivory", "Jabbering", "Jaded", "Jaunty",
            "Jaundice", "Jazzy", "Jealous", "Jiggly", "Jinchira", "Jittery", "Jiving", "Jocular", "Jocund", "Jodeling",
            "Jogging", "Jolly", "Jolted", "Jolty", "Jousting", "Jovial", "Joyous", "Jubilant", "Judicious", "Juggling",
            "Juicy", "Jumbled", "Jumping", "Jumpity", "Jumpy", "Jungle", "Jungly", "Jurassic", "Juvenile", "Katie",
            "Kafkaesque", "Kaleidoscopic", "Kamikaze", "Kanny", "Karmic", "Kayoed", "Keeking", "Keen", "Keepable",
            "Kempy", "Khaki", "Kick-ass", "Kicking", "Kicky", "Killer", "Kilted", "Kind", "Kindhearted", "Kingly",
            "Klutzy", "Kinetic", "King-sized", "Kinky", "Kissable", "Kissy", "Kitschy", "Kleptomaniacal", "Knavish",
            "Knightly", "Knobby", "Knotty", "Kooky", "Kurt", "Kvetching", "Lampooning", "Languid", "Lascivious",
            "Laudable", "Laughable", "Laughing", "Lazy", "Leaky", "Leal", "Leaping", "Leapy", "Leftist", "Lethal",
            "Liberal", "Limp", "Lingual", "Listless", "Lithe", "Litigious", "Lively", "Lofty", "Lonely", "Longhorn",
            "Loopy", "Loquacious", "Lordly", "Lovely", "Lucid", "Lucky", "Lugubrious", "Luminiferous", "Luminous",
            "Lurid", "Luscious", "Lusty", "Macular", "Mad", "Magical", "Magistical", "Magnanimous", "Magnetic",
            "Magnificent", "Maieutic", "Majestic", "Majim", "Majuscul", "Malapert", "Malicious", "Malodorous", "Malty",
            "Mammoth", "Mangy", "Manic", "Marauding", "Marvelous", "Massive", "Masterful", "Maudlin", "Maverick",
            "Mazarine", "Meandering", "Measured", "Meaty", "Melancholic", "Melic", "Melliferous", "Mellifluous",
            "Mellow", "Melodic", "Melodious", "Memorable", "Menacing", "Menstrual", "Mental", "Mercantile", "Mercenary",
            "Merciful", "Merciless", "Mercurial", "Meridian", "Merry", "Mesmeric", "Metallic", "Methodic(al)",
            "Meticulous", "Metric", "Mettled", "Mickle", "Mighty", "Mild", "Militant", "Mindful", "Mini", "Minimalist",
            "Minty", "Miraculous", "Mischievous", "Misty", "Mobile", "Modest", "Modish", "Momentous", "Monadic",
            "Monastic", "Monty", "Moonlight", "Moral", "Mordant", "Moxious", "Murphy", "Muscled", "Mushy", "Musky",
            "Musical", "Muttering", "Myriad", "Mysterious", "Mystic", "Mystical", "Mythical", "Nano", "Nasty", "Natty",
            "Naughty", "Nauseous", "Necrotising", "Nefarious", "Nerdy", "Nested", "Neurotic", "Nifty", "Nimble",
            "Nippy", "Noble", "Nocturnal", "Nomadic", "Normal", "Normandic", "Nostalgic", "Novel", "Null", "Nutritious",
            "Obedient", "Oblivious", "Obnoxious", "Obsequious", "Observing", "Obstreperous", "Obverse", "Obtuse",
            "Obvious", "Odd", "Occult", "Octal", "Octennial", "Oily", "Okay", "Omnific", "Omniscient", "Oneiric",
            "Opportune", "Opportunistic", "Opulent", "Oral", "Orderly", "Ordinary", "Orgasmic", "Orgiastic",
            "Origamist", "Ornery", "Orthodox", "Orthogenic", "Oscillating", "Ostentatious", "Acidic", "Pacific",
            "Panacean", "Parabolic", "Paradisaic", "Paramount", "Passive", "Peachy", "Pedantic", "Perceptive",
            "Perennial", "Persnickety", "Perky", "Persistent", "Perverse", "Phantastic", "Phantom", "Phat",
            "Philantropic", "Philosophical", "Phlegmatic", "Phobic", "Phooka", "Phlegmatic", "Photogenic", "Playful",
            "Psychedelic", "Psychic", "Pickled", "Pimping", "Pink Panther", "Plastered", "Plastic", "Plonky", "Plucky",
            "Plutonic", "Poetic", "Polyplastic", "Posh", "Pointy", "Precise", "Pokey", "Polished", "Powerful",
            "Powersaver", "Pragmatic", "Prancing", "Precocious", "Predatory", "Predictive", "Predominate",
            "Prestidigious", "Pretty", "Priapic", "Prickly", "Prideful", "Prissy", "Pristine", "Proactive", "Prolific",
            "Proud", "Prowly", "Prudent", "Pulchritudinous", "Purring", "Pyroclastic", "Pyromaniac", "Pyrotechnic",
            "Quaint", "Quaking", "Quantal", "Quantum", "Quarter", "Queer", "Querulous", "Quick", "Quiet",
            "Quintessential", "Quixotic", "Quirky", "Quivering", "Rabid", "Racey", "Racing", "Radiant", "Radical",
            "Rambunctious", "Rampant", "Rancid", "Randy", "Rapid", "Rational", "Raucous", "Raunchy", "Reasonable",
            "Rebel", "Rebellious", "Rednosed", "Resonant", "Rhapsy", "Ribald", "Rich", "Risky", "Roasted", "Robust",
            "Rolly", "Rowdy", "Rugged", "Runcible", "Ruthless", "Reminiscent", "Raring", "Saccate", "Saccharine",
            "Sagacious", "Sage", "Salivating", "Salubrious", "Sanguine", "Sarcastic", "Sardonic", "Sassy", "Saucy",
            "Scary", "Scrawny", "Screwy", "Secretive", "Selenographic", "Selenomorphic", "Sensual", "Sentimental",
            "Serendipitous", "Serious", "Servile", "Severe", "Sexy", "Sharp", "Shiny", "Shrewd", "Silly", "Skinny",
            "Slick", "Slim", "Slimmy", "Slinky", "Slippery", "Slippy", "Smelly", "Smiling", "Smitten", "Smooth",
            "Snappy", "Snazzy", "Sneaky", "Soaring", "Solid", "Sophisticated", "Sound", "Spastic", "Special",
            "Spectacular", "Speedy", "Spicy", "Spooky", "Spotty", "Sprightly", "Spunky", "Squidgy", "Squirly",
            "Stalwart", "Stealthy", "Stelene", "Steward", "Stocky", "Strapping", "Streetwise", "Stressful", "Striking",
            "Stunning", "Stupendous", "Sturdy", "Suave", "Suctorial", "Sudden", "Sultry", "Superstitious",
            "Surreptitious", "Swarthy", "Tabby", "Tactful", "Talented", "Tame", "Tantric", "Tangible", "Tangled",
            "Tanked", "Tasteful", "Tasty", "Taught", "Teachable", "Tedious", "Teeming", "Tempean", "Temperamental",
            "Temperate", "Tenable", "Tenacious", "Tender", "Terrific", "Thankful", "Therapeutic", "Thorough",
            "Thoughtful", "Thrashing", "Thrifty", "Thrilled", "Thrilling", "Thriving", "Ticklish", "Tidy", "Tight",
            "Timely", "Timeless", "Tiny", "Tipsy", "Tireless", "Tolerant", "Touching", "Tough", "Touted",
            "Trailblazing", "Tranquil", "Transgendered", "Transcendent", "Transcendental", "Transsexual", "Transparent",
            "Transpicuous", "Traumatized", "Traveled", "Treasured", "Tremendous", "Tretis", "Tricky", "Trim", "Trippy",
            "Triumphant", "True", "Truculent", "Trusted", "Trustful", "Trustworthy", "Trusty", "Truthful", "Twirling",
            "Tweaky", "Twitchy", "Tympanic", "Ubuntu", "Ugly", "Ultimate", "Unadulterated", "Unapologetic",
            "Unassailable", "Unassuming", "Unbelievable", "Ultrarelativistic", "Unctuous", "Underrated",
            "Underrepresented", "Understanding", "Undulating", "Unplugged", "Unpretentious", "Unrated", "Unrepentant",
            "Unruly", "Untamed", "Untapped", "Uppity", "Undead", "Uproarious", "Ubiquitous", "Utopic", "Valiant",
            "Vast", "Veracious", "Versatile", "Veteran", "Vibrant", "Violent", "Viral", "Virtuoso", "Vitriolic",
            "Vivacious", "Vivid", "Vociferous", "Volatile", "Voluptuous", "Vomiting", "Voracious", "Wandering", "Warm",
            "Warty", "Western Tragopan", "Wild", "Wily", "Wimpy", "Windy", "Witty", "Wobbly", "Wonderful", "Woolly",
            "Xanthic", "Xenodochial", "Xenolithic", "Xenophobic", "Xenial", "Xeric", "Xintillating", "Xiphoid",
            "Xylographic", "Xylophonic", "Yakkity", "Yammering", "Yelping", "Yiffy", "Yippity", "Youthful", "Yummy",
            "Yodeling", "Zany", "Zealous", "Zen", "Zesty", "Zippy", "Zooming", "Zarking"));
    private static List<String> animals = new ArrayList<String>(Arrays.asList("Aardvark", "Aal", "Affenpinscher",
            "Agama", "Albatross", "Alligator", "Alliteration", "Alpaca", "Amoeba", "Angelfish", "Anemone", "Anoa",
            "Ant", "Anteater", "Antelope", "Ape", "Arachnid", "Armadillo", "Asp", "Alien", "Axolotl", "Alebrije",
            "Baboon", "Badger", "Barnacle", "Barracuda", "Bat", "Beagle", "Bear", "Beaver", "Bee", "Beetle", "Bison",
            "Bitch", "Bittern", "Blackbird", "Blowfish", "Bluejay", "Bobcat", "Bonobo", "Bothrop", "Bowerbird", "Bunny",
            "Buck", "Bull", "Bugblatter Beast of Traal", "Camel", "Capybara", "Cardinal", "Caracal", "Cassowary", "Cat",
            "Caterpillar", "Centipede", "Chameleon", "Chapulín", "Cheetah", "Chickadee", "Chicken", "Chimp",
            "Chinchilla", "Chipmunk", "Chupacabra", "Coati", "Cobra", "Cockatoo", "Condor", "Cony", "Coot", "Cougar",
            "Cow", "Coyote", "Crane", "Crocodile", "Crow", "Crab", "Caribou", "Deer", "Devil", "Dingo", "Diplodocus",
            "Dodo", "Dog", "Dolphin", "Dormouse", "Dove", "Dragon", "Dzo", "Drake", "Duck", "Dugong", "Dungbeetle",
            "Doe", "Dryad", "Donkey", "Drop Bear", "Eagle", "Earthworm", "Earwig", "Echidna", "Eel", "Eft", "Eland",
            "Elephant", "Eagle", "Elf", "Elk", "Emu", "Escargot", "Ermine", "Euglena", "Ewe", "Falcon", "Fawn",
            "Feline", "Fenestrator", "Fennec", "Fenix", "Ferret", "Fieldmouse", "Finch", "Finfoot", "Firefly", "Fish",
            "Flamingo", "Fly", "Flight", "Foundling", "Fox", "Frog", "Fugu", "Fruitbat", "Furbolg", "Galah", "Gannet",
            "Gappu", "Gator", "Gazelle", "Gecko", "Gelding", "Gerbil", "Gibbon", "Giraffe", "Glider", "Gnarwhal",
            "Gnat", "Gnu", "Goat", "Gobbler", "Goblin", "Goldfinch", "Goose", "Gopher", "Gorilla", "Goshawk", "Grebe",
            "Groundhog", "Grue", "Gryphon", "Gull", "Guanaco", "Gurk", "Guppy", "Ghost", "Hamster", "Hare", "Harrier",
            "Hartebeest", "Hawk", "Hedgehog", "Hen", "Heffalump", "Heron", "Hippo(potamus)", "Hoopoe", "Hornet",
            "Horse", "Horus", "Hounddog", "Human", "Hummingbird", "Humpback", "Hyena", "Husky", "Hypnotoad", "Ibex",
            "Indri", "Ibis", "Icebear", "Iceweasel Wink ;)", "Ichtiosaurus", "Ichthyosaur", "Ifrit", "Iguana", "Impala",
            "Indri", "Insect", "Inkanyamba", "Imp", "Iguana", "Isopoda", "Irukandji", "Ivory Wink ;)",
            "Ichabodcraniosaurus", "Iguanodon", "Iguanoides", "Iguanosaurus", "Iliosuchus", "Ilokelesia",
            "Incisivosaurus", "Indosaurus", "Indosuchus", "Ingenia", "Inosaurus", "Irritator", "Isanosaurus",
            "Ischisaurus", "Ischyrosaurus", "Isisaurus", "Issasaurus", "Itemirus", "Iuticosaurus", "Jaybird", "Junebug",
            "Jabberwock", "Jacana", "Jackal", "Jackalope", "Jackass", "Jackrabbit", "Jaguar", "Javelina", "Jay",
            "Jellyfish", "Jackrabbit", "Jerboa", "Joey", "Jentink's", "Jubata", "Junco", "Kakapo", "Kalong", "Kangaroo",
            "Katydid", "Kea", "Kelpie", "Kestrel", "Kid", "Killdeer", "Kingfisher", "Kinkajou", "Kite", "Kittie",
            "Kitten", "Kittiwake", "Kittyhawk", "Kiwi", "Knight", "Koala", "Kodkod", "Kodiak", "Koi", "Kolibri",
            "Komodo", "Konqui", "Kookaburra", "Kouprey", "Kowari", "Kudu", "Kraut", "Krocodile", "Labrador", "Ladybug",
            "Lagomorph", "Lamantin", "Lamb", "Lamprey", "Lapwing", "Lark", "Leafhopper", "Leopon", "Leech", "Lemming",
            "Lemur", "Leopard", "Liger", "Limpet", "Lion", "Lizard", "Llama", "Lobster", "Loompa", "Loon", "Longhorn",
            "Lorax", "Loris", "Louse", "lycaon", "Lynx", "Macaque", "Macaw", "Macropod", "Maggots", "Magpie", "Mallard",
            "Mammoth", "Man", "Mandrill", "Manatee", "Manta", "Mantis", "Mara", "Mastiff", "Marlin", "Marmot",
            "Marsupilami", "Marten", "Meadowlark", "Meerkat", "Millipede", "Mink", "Minnow", "Mobutu", "Mockingbird",
            "Mole", "Mollusk", "Molly", "Monal", "Monca", "Mongoose", "Monkey", "Moose", "Mosquito", "Moth", "Motmot",
            "Mouflon", "Mouse", "Muskrat", "Muskox", "Monitor", "Mule", "Mustang", "Mutt", "Myna", "Naiad", "Narwhal",
            "Newt", "Nicholine", "Nightelf", "Nightingale", "Nightjar", "Ninf", "Numbat", "Nutria", "Nymph", "Ocelot",
            "Octopus", "Okapi", "Oompa-loompa", "Opossum", "Orangutan", "Orc", "Orca", "Oriole", "Oryx", "Ostrich",
            "Otter", "Owl", "Ox", "Oyster", "Pegasus", "Pademelon", "Panda", "Pangolin", "Panther", "Parakeet",
            "Parrot", "Partridge", "Peacock", "Peafowl", "Peccary", "Pelican", "Penguin", "Pheasant", "Phoenix",
            "Pichi", "Pig", "Pigeon", "Piglet", "Pika", "Piraña", "Piranha", "Pitbull", "Pixi", "Platypus", "Polecat",
            "Pony", "Porcupine", "Porpoise", "Possum", "Primate", "Pronghorn", "Protozoa", "Puffin", "Puma", "Python",
            "Quagga", "Quahog", "Quail", "Qantassaurus", "Quetzalcoatl", "Quetzal", "Quokka", "Quoll", "Rabbit",
            "Raptor", "Rat", "Raccoon", "Raptor", "Ratel", "Rattlesnake", "Raven", "Redbird", "Reindeer", "Rhea",
            "Rhino", "Robin", "Roadrunner", "Rook", "Rooster", "Rottweiler", "Roach", "Ringtail", "Sabretooth",
            "Salamander", "Salmon", "Saola", "Sasquatch", "Scallop", "Scorpion", "Scorpionfish", "Scottie", "Seagull",
            "Seahorse", "Seal", "Serval", "Shark", "Sheep", "Shih Tzu", "Shrew", "Silverfish", "Sitatunga", "Skunk",
            "Slippershell", "Sloth", "Snail", "Snake", "Snow Leopard", "Spaniel", "Sparrow", "Spider", "Springbok",
            "Squid", "Squirrel", "Stallion", "Starfish", "Stingray", "Sukko", "Swallow", "Swan", "Swordfish", "Satyr",
            "Snake", "Snapping Turtle", "Snapper", "Seadonkey", "Suricata", "Suricate", "Seahorse", "Tahr", "Taipan",
            "Takahe", "Tamandua", "Tapir", "Tarantula", "Tarsier", "Tasmanian Devil", "Tenrec", "Termite", "Terrapin",
            "Terrier", "Tiger", "Tigon", "Tigerfish", "Toad", "Tortoise", "Toucan", "Trogon", "Troll", "Trout",
            "Tuatara", "Turkey", "Turtle", "Tassie Thylacine", "Tazzy Thylacine", "Tesselated", "Uakari", "Ubuntu",
            "Uglybird", "Utonagan", "Ungulate", "Unicorn", "Urchin", "Urial", "Urubu", "Urukai", "Uguisu", "Umbrian",
            "Uintathere", "Veery", "Velociraptor", "Vervet", "Vicuña", "Viper", "Vixen", "Vizcacha", "Vole", "Vulture",
            "Wallaby", "Walrus", "Warthog", "Wasp", "Weasel", "Werewolf", "Weevil", "Whale", "Wildebeest", "Wolf",
            "Wolverine", "Wombat", "Woodchuck", "Woodpeck", "Worm", "Wren", "Weka", "Xebu", "Xenarthra", "Xenomorph",
            "Xenoturbella", "Xenops", "Xerus", "Xiphias", "Xipho", "X-ray fish", "Xue Bao", "Xoloitzcuintle", "Xólotl",
            "Yaffle", "Yak", "Yellowjacket", "Yeti", "Zealot", "Zebra", "Zebrafish", "Zebu", "Zorilla", "Zorse"));

    public String generate() {
        return adjectives.get(rand.nextInt(adjectives.size())) + " " + animals.get(rand.nextInt(animals.size()));
    }
}
