// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortunes.proto

package o.grpc.fortunes;

public interface FortuneResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fortunes.FortuneResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
