// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortunes.proto

package o.grpc.fortunes;

public final class FortuneProto {
  private FortuneProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fortunes_FortuneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fortunes_FortuneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fortunes_FortuneResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fortunes_FortuneResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016fortunes.proto\022\010fortunes\"\036\n\016FortuneReq" +
      "uest\022\014\n\004name\030\001 \001(\t\"\"\n\017FortuneResponse\022\017\n" +
      "\007message\030\001 \001(\t2T\n\016FortuneService\022B\n\tenli" +
      "ghten\022\030.fortunes.FortuneRequest\032\031.fortun" +
      "es.FortuneResponse\"\000B(\n\017o.grpc.fortunesB" +
      "\014FortuneProtoP\001\242\002\004FRTNb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fortunes_FortuneRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fortunes_FortuneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fortunes_FortuneRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_fortunes_FortuneResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fortunes_FortuneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fortunes_FortuneResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
