// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortunes.proto

package o.grpc.fortunes;

public interface FortuneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fortunes.FortuneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
