// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortunes.proto

package o.oo.grpc.fortunes;

public final class FortuneService {
  private FortuneService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_o_oo_grpc_fortunes_FortuneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_o_oo_grpc_fortunes_FortuneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_o_oo_grpc_fortunes_FortuneResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_o_oo_grpc_fortunes_FortuneResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016fortunes.proto\022\022o.oo.grpc.fortunes\"\036\n\016" +
      "FortuneRequest\022\014\n\004name\030\001 \001(\t\"\"\n\017FortuneR" +
      "esponse\022\017\n\007message\030\001 \001(\t2`\n\007Fortune\022U\n\010r" +
      "etrieve\022\".o.oo.grpc.fortunes.FortuneRequ" +
      "est\032#.o.oo.grpc.fortunes.FortuneResponse" +
      "\"\000B\022B\016FortuneServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_o_oo_grpc_fortunes_FortuneRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_o_oo_grpc_fortunes_FortuneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_o_oo_grpc_fortunes_FortuneRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_o_oo_grpc_fortunes_FortuneResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_o_oo_grpc_fortunes_FortuneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_o_oo_grpc_fortunes_FortuneResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
